### ISSUE TITLE
Move Batch Table to after features payload (glTF, points, vector data)?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#103]
From https://github.com/AnalyticalGraphicsInc/cesium/pull/4112/files#r70846940

> in b3dm and i3dm, the batch table comes before glTF. We should be consistent here for now and move the positions payload after the batch table; however, we might want to switch them all later if there is a benefit, e.g., to avoid parsing it in some cases?

**Comment by pjcozzi** [comment]
We should also make sure the header fields are consistent, e.g., in `pnts` if the batch table comes after the points payload then the header should keep `pointsLength`, `batchTableJSONByteLength`, `batchTableJSONBinaryLength` in that order.

**Comment by pjcozzi** [comment]
CC #32

**Comment by lilleyse** [comment]
In the current state, should `batchLength` go after `batchTableLength` in b3dm?

https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel

**Comment by pjcozzi** [comment]
> In the current state, should batchLength go after batchTableLength in b3dm?

> https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel

Yes, but I would leave it until we address this issue all at once; pnts is also inconsistent right now.

**Comment by pjcozzi** [comment]
i3dm now has feature table then batch table, #100.

**Comment by pjcozzi** [comment]
@lasalvavida @lilleyse and I discussed.  The general layout of a tile is
```
[header][feature table][batch table][glTF]
```
So b3dm is fine as is since it doesn't have a batch table.

The only change this issue needs is:

> In the current state, should batchLength go after batchTableLength in b3dm?

> https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel

**Comment by lilleyse** [comment]
I'm leaning towards `batchLength` being last in the header because it's like an extra field when compared to the other tile formats, and matches the [batchTable][gltf] ordering.

**Comment by pjcozzi** [comment]
> I'm leaning towards batchLength being last in the header because it's like an extra field when compared to the other tile formats, and matches the [batchTable][gltf] ordering.

Yes, agreed, I thought that is what you suggested above.

**Comment by pjcozzi** [comment]
> I'm leaning towards batchLength being last in the header because it's like an extra field when compared to the other tile formats, and matches the [batchTable][gltf] ordering.

@lilleyse when you upload all the .b3dm files in the Cesium repo, it could be a great opportunity to make sure they are all as small as possible so we minimize the repo's size.

**Comment by lilleyse** [comment]
Ah yeah, good idea. They are 50-60 KB currently for 100 buildings per tile. I could get them down about ~10 KB each.

**Comment by pjcozzi** [comment]
@lilleyse can you please link this issue to the Cesium PR that swaps `batchLength` and `batchTableLength`, and the spec update PR (it doesn't exist yet, right?)?

**Comment by lilleyse** [comment]
Implementation of the b3dm header changes is in https://github.com/AnalyticalGraphicsInc/cesium/pull/4228

**Comment by pjcozzi** [comment]
Spec updates: #4183

**Comment by pjcozzi** [comment]
#125 will be merged shortly.
