### ISSUE TITLE
How to use  A 3D Tiles way to deal with 20000 gltf files

### ISSUE THREAD

**Issue by liyihongcug** [AnalyticalGraphicsInc/3d-tiles#107]
I use ceasium to publish  20000 gltf files which are converted  from oblique photograph data --  osgb file by unmanned aerial vehicle.
Those files are distributed in 25 file p ackages. The  file packages' name are like Tile_+000_+000，Tile_+000_+001,Tile_+000_+002,，Tile_+000_+003,Tile_+000_+004,
...............   Tile_+004_+000, Tile_+004_+001, Tile_+004_+002, Tile_+004_+003, Tile_+004_+004.
Now I only select 2 file packages(Tile_+000_+000，Tile_+000_+001).
Tile_+000_+000 includes 800 gltf files
Tile_+000_+001 includes 1800 gltf files.
How to use   3D Tiles way to deal with oblique photograph data (20000 gltf files)?
1  I know we can use quad tree algorithm to divide One 3d tiles. But now My data are 20000 gltf files.
How to deal with it?
2  I want to know whether we can get 3d tiles tool if exists?

**Comment by pjcozzi** [comment]
@liyihongcug thanks for the interest.

Next Saturday, @lilleyse and I are presenting a tutorial on 3D Tiles that will cover many tiling algorithms at Web3D: http://cesiumjs.org/2016/07/12/Web3D-2016/.  The slides and video will be posted afterward and may help you come up with a nice tiling algorithm for your particular data.  Keep an eye on the Cesium blog.

AGI - the company that started Cesium and 3D Tiles - is also creating a service to tile a variety of massive datasets.  It is not ready yet, but you can get more info here: https://cesiumjs.com/

**Comment by fanvanzh** [comment]
you can try my project which is very fast to convert osgb to 3dtile
