### ISSUE TITLE
Update tile figure

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#110]
https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/figures/tile.png

For #101, #99, and any other updates.

**Comment by lilleyse** [comment]
The image doesn't contain `viewerRequestVolume` but otherwise I think it's fine to close this.
Updated image: https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/1.0/figures/tile.png
