### ISSUE TITLE
Consistent normals between pnts and i3dm

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#119]
@lilleyse why does pnts use `NORMAL`/`NORMAL_OCT16P` instead of `NORMAL_UP`/`NORMAL_RIGHT` (and `NORMAL_UP_OCT32P`/`NORMAL_RIGHT_OCT32P`) like i3dm?

16P is, of course, still OK for pnts.

**Comment by lilleyse** [comment]
Because i3dm normals need to represent a wider range of rotations, including roll rotations about the axis it's on, whereas points just need the plain normal that a vertex attribute would have.

**Comment by pjcozzi** [comment]
Couldn't `pnts` use the `i3dm` representation since it is more concise and would be consistent?

**Comment by lasalvavida** [comment]
I think that what @lilleyse is saying is that the `pnts` normal is for lighting, not orientation.

**Comment by lilleyse** [comment]
@lasalvavida Yeah exactly. If anything the names `NORMAL_UP` and `NORMAL_RIGHT` may be misleading.

**Comment by pjcozzi** [comment]
Ah nevermind, I was thinking of taking advantage of the fact that the normal is of unit length to only have to store two components.  I think we would have to know the direction of the third component though.
