### ISSUE TITLE
License for the spec text

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#12]
[CC BY 4.0](http://creativecommons.org/licenses/by/4.0/) is probably fine.  See [Considerations for licensors and licensees](https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees#Considerations_for_licensors).

However, it could be useful to have the same CLA as Cesium for when the community contributes spec fixes, new tile formats, etc.

**Comment by pjcozzi** [comment]
> However, it could be useful to have the same CLA as Cesium for when the community contributes spec fixes, new tile formats, etc.

CLA assistant with a simple CLA (like we use for the [WebGL 2 Samples](https://gist.github.com/pjcozzi/4d1ab2166519de7ba41b)) could also work.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/308
