### ISSUE TITLE
Sample hierarchical point cloud tileset

### ISSUE THREAD

**Issue by connormanning** [AnalyticalGraphicsInc/3d-tiles#128]
I am looking for a sample point cloud tileset that contains `children` tiles, but haven't been able to find one.  For example, all of [these](https://github.com/AnalyticalGraphicsInc/cesium/tree/3d-tiles/Specs/Data/Cesium3DTiles/PointCloud) seem to be only a root tile.

I've downloaded the entire Chappes tileset (which is used in [this demo](https://cesiumjs.org/Chappes/index.html)) but it doesn't seem to match the current 3DTiles point cloud specification - so I'm thinking it's outdated and that the demo is running an older version of the library.

My end goal is to create my own point cloud tilesets that work with the current `3dtiles` branch of Cesium.  So far I've created a test set with a root and single child tile, but I am having some display issues with the child tile.  This is why I'm looking for a hierarchical sample to compare against -  does one exist?  Apologies if I've missed one in an obvious location.

**Comment by lilleyse** [comment]
None exist at the moment in the main cesium repo, but this would be a good thing for us to add in the samples repo: https://github.com/AnalyticalGraphicsInc/3d-tiles-samples. I should be able to generate something pretty soon.

**Comment by lilleyse** [comment]
I just threw this together quickly, it's probably too simple to host in the 3d-tiles-samples repo though so here it is:

[PointCloudLayered.zip](https://github.com/AnalyticalGraphicsInc/3d-tiles/files/471138/PointCloudLayered.zip)

![capture](https://cloud.githubusercontent.com/assets/915398/18497743/06e7831e-79ff-11e6-9d6d-a89414c5d7b1.PNG)

Yeah the Chappes demo is out of date, thanks for the reminder that we need to update it.
