### ISSUE TITLE
3D Tile-to-Globe Alignment

### ISSUE THREAD

**Issue by KermMartian** [AnalyticalGraphicsInc/3d-tiles#139]
In taking our 3D models that we had previously placed in the world as, well, models and turning them into 3D tile elements, I've run into the necessity of translating and rotating the local coordinate systems in the 3D tile models. With simple 3D models, we would take the .glb model and a base (latitude, longitude, altitude), and load with the model transform:
`Cesium.Transforms.eastNorthUpToFixedFrame(Cesium.Cartesian3.fromDegrees(lon, lat, alt));`

Now, we need to bake those transforms into our tileset.json files, as far as I can tell, both performing the necessary WGS84 conversions to turn that base point into (x,y,z) (which we currently do) and to rotate the model to be normal to the surface of the globe at that point (which we do not yet do). Broadly, is there any functionality available currently to do that automatically? I'm also acutely aware that for 3D tiles that cover increasingly large areas, terrain and structure models that assume the surface of the earth are flat will run into substantial problems, especially where the edges of tiles meet.

Thanks in advance for any advice on handling this with 3D tiles. (Also @elfprince13)

**Comment by KermMartian** [comment]
I apologize, I should have phrased that more clearly. We are baking the transforms into the tile transforms in tileset.json files, not into the models themselves. I was curious if there was a flag, option, callback, or other method to automatically generate the proper transformation matrix in Cesium from a base point, either that I overlooked or that was planned for the future, to avoid having to replicate a version of its code that turns local coordinates + lat, lon, altitude into global Cartesian coordinates in our own tileset.json generator. It sounds like there's not; thanks for that clarification!

**Comment by lilleyse** [comment]
Ah I think I see now, so you would interested in specifying the base lat, lon, altitude in the tileset somewhere, which could then be converted to WGS84 and transform the tileset automatically on load?

This isn't an automatic solution, but it might work ok - store the lat, lon, altitude in the `asset` section of the tileset and once the tileset's ready promise resolves, calculate the transform with `eastNorthUpToFixedFrame` (as above) and set the tileset's `modelMatrix`. Though this solution may not work that well if you want to do this for individual tiles.

Hopefully I didn't misinterpret your question again, let me know how it sounds.

**Comment by KermMartian** [comment]
No, not at all; I didn't phrase it sufficiently clearly the first time. That sounds like a very reasonable solution to me, and I'll give it a try. I wouldn't bother you about a one-off implementation question in an issue like this, except that I suspect others using 3D tiles might want to perform the same operation. Thanks again!

**Comment by KermMartian** [comment]
For the curious, I ended up exploring Sean's suggestion, and due to the complexity of doing it in the client, I ended up making the offline tileset.json generation script add the rotation + translation as tile transforms (keeping track, of course, of adjusting each tile's transformation to take its parent's transformation into account.
