### ISSUE TITLE
Shader styling considerations

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#140]
Point cloud styling engines may often use a shader implementation. Currently the spec is written with a bias towards JavaScript and its implicit type conversions and ability to check equality between different types, which are not possible in a language like GLSL 1.0. Shader implementations will also have major issues with strings and regular expressions. We need to decide what aspects of the styling language can be supported for stricter languages like GLSL and C++.
- [ ] **Shader Styling**
  - [ ] Unsupported:
    - [ ] `isNan`, `isFinite`(supported in later versions of GLSL with `isnan` and `isinf`)
    - [ ] Strings, not supported in the GLSL styling engine or the batch table binary
      - [ ] This includes accessing color components like `color()["r"]` or vectors with `vec4(1.0)["x"]`
    - [ ] Regular expressions
    - [ ] Arrays that aren't length 2, 3, or 4 (technically supported but cumbersome to use)
    - [ ] null and undefined - use a default value like 0? https://github.com/AnalyticalGraphicsInc/cesium/issues/4637
    - [ ] type mismatching - comparing floats to bools to vectors will result in shader compilation errors
    - [ ] Index out of bounds for arrays/vectors/colors will result in shader compilation errors whereas it returns undefined in JS

More discussion here: https://github.com/AnalyticalGraphicsInc/cesium/pull/4336#issuecomment-250238675

**Comment by pjcozzi** [comment]
To scope this for 1.0, I think we can just add some _Implementation Notes_ like the glTF spec.

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
