### ISSUE TITLE
How Can I compute the geometricerror

### ISSUE THREAD

**Issue by wbhshy** [AnalyticalGraphicsInc/3d-tiles#162]
hi,This problem has troubled me for a long time，could you teach me how to compute the geometricerror?

**Comment by lilleyse** [comment]
The geometric error can be computed however you like, but often a good estimate is finding the diagonal of the largest building/feature in the tile. In tileset.json a tile's geometric error will often equal the largest geometric error of its children. Typically leaf tiles have a geometric error of 0.

**Comment by CrashedBboy** [comment]
Hi @lilleyse ,
So, if I have a model  which its diagonal is 10 meters long,  it's proper to set the value of `geometricError` to 10, right?

**Comment by lilleyse** [comment]
Yes that could work. I should reiterate though that `geometricError` doesn't have an exact formula and using the diagonal may not look correct in all situations.
