### ISSUE TITLE
Update b3dm models or spec

### ISSUE THREAD

**Issue by ibesora** [AnalyticalGraphicsInc/3d-tiles#163]
There is no correspondence between the b3dm models used in the new york example and the spec.
The b3dm models have the old 20 byte header instead of the 24 byte ones although they work fine on the last version of the 3d-tiles branch.
If the old header will still be supported there should be some part of the spec explaining that. If not, the b3dm models should be updated.

**Comment by lilleyse** [comment]
The old header format is supported in Cesium as a fallback since a lot of datasets including New York haven't been re-processed yet. For the spec, only the 24 byte header is valid. Thanks for the reminder about updating NYC.
