### ISSUE TITLE
Batched 3d model spec readme error

### ISSUE THREAD

**Issue by ibesora** [AnalyticalGraphicsInc/3d-tiles#164]
There is an error on the Batched 3d model spec readme file. 
On the second paragraph of the binary glTF section says "Binary glTF immediately follows the batch table. It begins **20** + batchTableByteLength bytes from the start of the arraybuffer " when it really starts at **24** + batchTableByteLength bytes from the start

**Comment by lilleyse** [comment]
Thanks for catching this @ibesora. A fix will be in soon.

**Comment by pjcozzi** [comment]
Fixed in #165.

Thanks again for the report, @ibesora!  Are you building something cool with 3D Tiles?  Have a link to a demo?

**Comment by ibesora** [comment]
Not really @pjcozzi, just a converter from geojson to 3D Tiles via b3dm.
I'll surely do something more with 3D Tiles and then I'll send you a link to a demo.
Keep up the good work!
