### ISSUE TITLE
Is there a way to adjust the height of model

### ISSUE THREAD

**Issue by zzcyrus** [AnalyticalGraphicsInc/3d-tiles#168]
I found the model under the terrain, is there any way to adjust the height of the model, I have tried to change the coordinate in the tileset.json but it didn't work.

By the way, I use smart3D software to create the model.

Thank you.

**Comment by lilleyse** [comment]
You can use the `modelMatrix` property of the tileset. This code snippet might help:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    scene3DOnly : true
});

var scene = viewer.scene;

var heightOffset = 23.0;
var url = '../../../Specs/Data/Cesium3DTiles/Tilesets/Tileset';
var tileset = scene.primitives.add(new Cesium.Cesium3DTileset({
    url : url
}));

tileset.readyPromise.then(function(tileset) {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0, -2.0, 0));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
    // Position tileset
    var cartographic = Cesium.Cartographic.fromCartesian(boundingSphere.center);
    var surface = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, 0.0);
    var offset = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, heightOffset);
    var translation = Cesium.Cartesian3.subtract(offset, surface, new Cesium.Cartesian3());
    tileset.modelMatrix = Cesium.Matrix4.fromTranslation(translation);
    console.log(tileset.modelMatrix);
});
```

**Comment by lilleyse** [comment]
That's for the Cesium implementation by the way. In the spec you may be interested in the [tileset.transform](https://github.com/AnalyticalGraphicsInc/3d-tiles#tile-transform) property.

**Comment by zzcyrus** [comment]
It works perfectly! Really thanks.

It seems that I have to work harder on the read.md :)

**Comment by lilleyse** [comment]
I'm glad it works!

**Comment by zouyaoji** [comment]
To adjust the height of terrain, is there a way to automatically calculate the most suitable heightOffset value?

**Comment by OmarShehata** [comment]
@zouyaoji if you're using CesiumJS, there's probably a few ways you can handle this depending on what you're trying to accomplish. I encourage you to post your question on the Cesium community forum and we can move the discussion there: https://community.cesium.com/
