### ISSUE TITLE
Option/extension for draco point compression

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#188]
See https://github.com/KhronosGroup/glTF/pull/874

**Comment by pjcozzi** [comment]
Quick stats: 10-25x better than gzip.  Decode 110 MB in JavaScript in 1 second.

**Comment by ggetz** [comment]
For b3dm and i3dm, this should be handled by the gltf extension itself. Probably mention in a non-normative section that the extension is available.

Point clouds and draco would target post 1.0

**Comment by pjcozzi** [comment]
Added in #310 (still open).

**Comment by pjcozzi** [comment]
@ggetz OK to close this?
