### ISSUE TITLE
Support RTC_CENTER for i3dm

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#189]
Better precision for instanced models has been requested at least twice. I don't see the harm in supporting RTC_CENTER just as we do for pnts and CESIUM_RTC for glTFs within b3dm's.

**Comment by pjcozzi** [comment]
OK with me.

See https://groups.google.com/forum/#!topic/cesium-dev/Dgi4zpodWXo

**Comment by lilleyse** [comment]
Also https://groups.google.com/forum/#!topic/cesium-dev/C7-7VWR8V9Q

**Comment by pierotofy** [comment]
+1 for this. Just adding a RTC_CENTER global semantic property would make it easier (and in some instances, more precise) than using POSITION_QUANTIZED and QUANTIZED_VOLUME_OFFSET.

**Comment by pjcozzi** [comment]
Thanks for the input, @pierotofy!

Added in #190.
