### ISSUE TITLE
Points : reuse of Potree could save time and speed up onboarding time

### ISSUE THREAD

**Issue by s093294** [AnalyticalGraphicsInc/3d-tiles#19]
We use photoscan to put images together and one of the nices things here is that it nativly support export to potree as a zip file. 

The potree project has been under its way for some time and has tools for generating trees. 

I am thinking that it would make sense to talk with the author about points and look into if it makes sense to reuse as much as possible, due to the tooling support already. Otherwise leaving all of us to solve one more tooling pipeline :)

Looks good btw. Happy to see the path AGI/Cesium is taking.

**Comment by pjcozzi** [comment]
I agree it would be cool if potree could export 3D Tiles.  The Cesium team is also going to develop conversion tools for point clouds, but it is best for the ecosystem if there are multiple tools.

**Comment by pjcozzi** [comment]
I want to keep this repo focused on 3D Tiles **spec** issues.  Please submit an issue to potree if you want to try to move this forward, just give them a warning that the spec - especially point clouds - is still being worked on.
