### ISSUE TITLE
tile tool

### ISSUE THREAD

**Issue by lihuadong1988** [AnalyticalGraphicsInc/3d-tiles#191]
excuse me,i want to generate 3d tiles,but i don't know how to do it,is there any tools that i can use?

**Comment by lilleyse** [comment]
Here are some starter tools: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools

If you create a post on https://groups.google.com/forum/#!searchin/cesium-dev/ instead someone can offer more advice based on what type of source data you have. We try to keep this github page for spec-related issues.
