### ISSUE TITLE
Additional fields for points?

### ISSUE THREAD

**Issue by mpgerlek** [AnalyticalGraphicsInc/3d-tiles#20]
Point cloud data is typically more than 3 fields for (x,y,z): LAS classification, salinity and temperature, etc., any of which one might want to represent by mapping it into (r,g,b).

Is there a plan to expand the binary blob in the point tile to include fields beyond (x,y,z) and allow for a colorization function to be plugged in, or is the intent that such colorization be done dynamically on the server side and passed back by the (r,g,b) fields?

**Comment by pjcozzi** [comment]
> Is there a plan to expand the binary blob in the point tile to include fields beyond (x,y,z) and allow for a colorization function to be plugged in

Yes.  This is what "attributes" mean in "needs compression and additional attributes" in the spec.

I don't know exactly how we will organize this yet, but here's how we do it for [3d models](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/b3dm/README.md).  Note that there is a lot of flexibility: the most commonly used attributes can be baked into the tile, and less commonly used attributes can be kept on a server and accessed with an id attribute from the title.  We do this for 3D buildings, e.g., building height is included in the tile for shading by height and zooming to the building, but the building address is queried on-demand for display when the building is clicked.

**Comment by mpgerlek** [comment]
Excellent, thanks.

(The spec looks simple and sufficient enough for me to try and output 3d-tiles support from my lidar tools, will let you know how it goes...)

**Comment by pjcozzi** [comment]
Cool, the point cloud tile loader is here: https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/Points3DTileContentProvider.js
