### ISSUE TITLE
Example pointcloud data set?

### ISSUE THREAD

**Issue by mpgerlek** [AnalyticalGraphicsInc/3d-tiles#21]
I'm not having any luck getting Cesium to display my own generated 3d-tiles data set, so I pulled down all the Chappes demo data and tried to get that to display like http://cesiumjs.org/Chappes/ does -- but no joy there either. I'm clearly doing something wrong, but don't have a working example I can try to compare against.

It would be _very_ helpful it you could put into the examples directory a very simple test dataset (the json and the actual tiles, plus the couple lines need to include in the HelloWorld sample app). Doesn't have to be the Chappes data, just a few tiles with few hundred points each.

Thanks much.

**Comment by pjcozzi** [comment]
We'll post some simple point cloud data when we start working on point clouds; we are currently finishing the glTF spec, which 3D Tiles uses for 3D buildings (batched models).

**Comment by pjcozzi** [comment]
This is part of the tests we are adding now for https://github.com/AnalyticalGraphicsInc/cesium/issues/3177.  Subscribe to that issue.
