### ISSUE TITLE
Relax external tileset restrictions

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#211]
From the spec:

```
root.geometricError === tile.geometricError,
root.refine === tile.refine, and
root.boundingVolume === tile.content.boundingVolume (or root.boundingVolume === tile.boundingVolume when tile.content.boundingVolume is undefined).
root.viewerRequestVolume === tile.viewerRequestVolume or root.viewerRequestVolume is undefined.
```

Are these restrictions actually needed? This makes serving dynamic external tilesets harder.

**Comment by lilleyse** [comment]
@pjcozzi any thoughts here? Loosing the restricts should not present much of a problem for clients.

**Comment by pjcozzi** [comment]
The intention was to prevent senseless consistences and to semantically treat the tileset's root as the other tileset's leaf tile...all in the name of making the traversal implementation easier in theory.

If these restrictions do not help the implementation in practice and it would not be possible to make technically valid but problematic tilesets then let's relax the restrictions.

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
