### ISSUE TITLE
Uppercase 'add' and 'replace'

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#230]
Should 'add' and 'replace' be 'ADD' and 'REPLACE' to help signify they are constant values?

From https://github.com/AnalyticalGraphicsInc/cesium/pull/5308#discussion_r119870866

**Comment by pjcozzi** [comment]
Copy glTF, which I think users upper case.  Cesium will need backwards compatibility for awhile.
