### ISSUE TITLE
Consult Cesium 3dtiles techniques

### ISSUE THREAD

**Issue by loveaniu** [AnalyticalGraphicsInc/3d-tiles#237]
> Mainly about “cesium 3dtiles”：I use tools from github,Convert model files(.max) to files in gltf format,Then turn the gltf file into an GLB file,In the process of converting the GLB file to 3dtiles,I don't know the rules for generating tileset.json files,I don't understand what the nodes represent in the tileset.json file,It will not appear as expected when the browser loads.Can you help me explain the meaning of each node in the tileset.json file?
> Other,I mainly refer to the example of "https://cesiumjs.org/NewYork/",Implement the same functionality,But my model files only have 18 buildings,Want to go through the form of 3dtiles?Want to achieve through the form of 3dtiles, select a single building.
> I want to capture the properties of a building by mouse events and highlight it.

**Comment by pjcozzi** [comment]
@loveaniu as I mentioned in my email, please use the [Cesium forum](http://cesiumjs.org/forum.html).  We use this GitHub repo for spec discussion and writing.  Thanks!

**Comment by loveaniu** [comment]
ok,thanks
