### ISSUE TITLE
osgb to 3d tiles?

### ISSUE THREAD

**Issue by xyjwyq** [AnalyticalGraphicsInc/3d-tiles#245]
Is there a tool to convert osgb to 3d tiles?

**Comment by pjcozzi** [comment]
I'm not currently aware of one, but if you have the source data used to create the OSG scene, the Cesium team may have a pre-release of a converter.  See https://groups.google.com/forum/#!topic/cesium-dev/xLkYIuku9hA

**Comment by fanvanzh** [comment]
[try this](https://github.com/fanvanzh/3dtiles)
