### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by m-schuetz** [AnalyticalGraphicsInc/3d-tiles#259]
The links to the selected talks on this page seem to be broken: https://github.com/AnalyticalGraphicsInc/3d-tiles

e.g.
* https://cesium.com/presentations/Web3D-2016-3DTilesTutorial.pptx
* https://cesium.com/blog/presentations/FOSS4GNA2016/3DTiles.pdf
* https://cesium.com/presentations/3D-Tiles-OGC-DC.pdf
* https://cesium.com/blog/presentations/SIGGRAPH2015/Cesium3DTiles.pdf

**Comment by lilleyse** [comment]
Thanks @m-schuetz. The links should be fixed once https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/260 is in.

**Comment by pjcozzi** [comment]
Good eye, thanks @m-schuetz @lilleyse!
