### ISSUE TITLE
3d tiles archive extension

### ISSUE THREAD

**Issue by Vineg** [AnalyticalGraphicsInc/3d-tiles#267]
As I can see, right now tileset is consist of a directory with loads of distinct files and folders. I think, it would be nice to introduce some kind of archive format with custom extension for purpose of simple transfering and identification.

**Comment by lilleyse** [comment]
Check out https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/89 for discussion about this. Our solution right now is to store the tileset in a SQLite database.

There is also a tool in `3d-tiles-tools` that can convert a tileset folder to a `.3dtiles` database file: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/tools#tilesettodatabase
