### ISSUE TITLE
Update Tile diagram

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#27]
* [ ] Remove `type`, #5
* [ ] Remove `batchSize`, #4

https://github.com/AnalyticalGraphicsInc/3d-tiles/raw/master/figures/tile.png

![](https://github.com/AnalyticalGraphicsInc/3d-tiles/raw/master/figures/tile.png)

**Comment by pjcozzi** [comment]
@slchow can you please update this image?

* [ ] Remove `type`
* [ ] Remove `batchSize`
* [ ] Change `box` to `boundingVolume`

As I attempted to illustrate here:

![img_0365](https://cloud.githubusercontent.com/assets/782098/13617195/68331f6e-e54b-11e5-8258-e84967fd0227.JPG)

The schema is here:
* [tile](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/tile.schema.json)
* [content](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/tile.content.schema.json)
* [boundingVolume](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/boundingVolume.schema.json)

**Comment by slchow** [comment]
![tile3](https://cloud.githubusercontent.com/assets/13438328/13625431/b546d27a-e585-11e5-96da-8d39aeacc8fb.png)

**Comment by slchow** [comment]
@pjcozzi  How does this look? Let me know if you need changes. When it's final I'll also send the eps.

**Comment by pjcozzi** [comment]
Thanks.  Can we make a few tweaks:

* `bounding volume` should be `boundingVolume` (these should match the format's actual names)
* `geometric error` should be `geometricError`
* Region should be more curved like this (see how it curves around Earth):

![image](https://cloud.githubusercontent.com/assets/782098/13636788/d25f51ec-e5d1-11e5-9646-56cef318a2bf.png)


When this is ready, can you open a PR to update the .eps and .png file here: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/figures

**Comment by pjcozzi** [comment]
Also, `Tile` should be `tile`.

**Comment by pjcozzi** [comment]
Updated in #83.
