### ISSUE TITLE
Relative URL : ambiguity on URL root

### ISSUE THREAD

**Issue by Groutcho** [AnalyticalGraphicsInc/3d-tiles#272]
In the `tileset.json` spec, it is specified that tile URLs can either be relative or absolute. In the case of a relative URL that happens in a non-root tileset, it is unclear whether the URL should be created starting from the root tileset, or the non-root tileset.

Example:
```
tileset.json
   anotherTileset.json
      tile.b3dm
```
Given that the URL to `tileset.json` is  `www.example.com/tileset.json`, what is the absolute URL of tile.b3dm ? Is it `www.example.com/tile.b3dm` or `www.example.com/anotherTileset/tile.b3dm` ?

**Comment by lilleyse** [comment]
This should stay open because the wording in the text could be clearer, but from the [schema](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/tile.content.schema.json):

> A string that points to the tile's contents with an absolute or relative url. When the url is relative, it is relative to the referring tileset.json.

So the absolute url would be `www.example.com/anotherTileset/tile.b3dm`

**Comment by Groutcho** [comment]
Thanks, I didn't think about consulting the schema.

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
