### ISSUE TITLE
The mechanism of Cesium to implement the request, render and delete of 3dtiles data

### ISSUE THREAD

**Issue by caohaoze** [AnalyticalGraphicsInc/3d-tiles#275]
I want to know the relationship between Cesium runtime(the request, render and delete of tile data) and 3D Tiles data(the boundingVolume, viewerRequestVolume and content.boundingVolume). Does anyone knows these details? Please share. Thanks.

**Comment by caohaoze** [comment]
and the relationship to memory, browser cache

**Comment by caohaoze** [comment]
and the relationship to PC memory, browser cache

**Comment by caohaoze** [comment]
Ping @pjcozzi

**Comment by lilleyse** [comment]
Hi @caohaoze, sorry for the delay. I'll try to post a quick summary later today or tomorrow on the [cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). Our github page is meant primarily for bug tracking and feature requests.

**Comment by caohaoze** [comment]
Can you send an email to my mailbox? It is not easy for me to visit the Google forum in China.
My mailbox is caohaoze@qq.com

**Comment by lilleyse** [comment]
Hi @caohaoze, I sent you an email. Feel free to respond to my email directly.
