### ISSUE TITLE
Convert DAE to b3dm and titleset.json

### ISSUE THREAD

**Issue by JJch331** [AnalyticalGraphicsInc/3d-tiles#281]
Hello,

We have a .dae file and want to use Cesium3DTileset to show 3D View likes [this](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Photogrammetry.html&label=3D%20Tiles)
I converted .dae to .gltf (also producing .bin .glsl .jpg) by COLLADA2GLTF , converted it to .glb by Geopipe/gltf2glb and then converted .glb to b3dm by 3d-tiles-tools.

But I just got a b3dm file, didn't it right ?
And I not sure how to produce tileset.json correctly.

Thanks for response.

**Comment by spatialhast** [comment]
try convert .dae to .obj and then to b3dm using `objTo3d-tiles` tool (https://github.com/PrincessGod/objTo3d-tiles). There is clear instruction how to create tileset.json file

**Comment by lilleyse** [comment]
@JJch331, the tiling approach can vary a lot based on the type of input data. @spatialhast's solution should work, though you may not see much performance benefit by creating a tileset with a single b3dm tile.

If you want to discuss 3D Tiles conversion in more detail, feel free to open a thread on the [Cesium Forum](https://cesiumjs.org/forum/). We use Github's issue tracker primarily for bugs or feature requests related to the 3D Tiles spec.

**Comment by JJch331** [comment]
Hi @lilleyse  and @spatialhast ,
thanks for your kindly comment. I got the tileset.json that looks like we want, but d3dm file seems has some problem in loading. I will read and discuss on the Cesium Forum.

**Comment by GongYangGitHub** [comment]
da

**Comment by GongYangGitHub** [comment]
anyone use 3d tiles in Unity3D？
