### ISSUE TITLE
Is it OK to use componentType of 5125(UNSIGNED_INT) to store _BATCHID rather than 5123(UNSIGNED_SHORT)?

### ISSUE THREAD

**Issue by caohaoze** [AnalyticalGraphicsInc/3d-tiles#285]
Now I want to create the buildings of the whole city by 3D Tiles. I will use the refine(replace) attribute in the {tileset.json} because the source data has HLOD. In this case, the root node of quadtree in the tileset has a b3dm file which contains the coarsest models of all buildings in the city. The number of buildings is above 65536, so the UNSIGNED_SHORT can not store all batchid. Can I use the UNSIGNED_INT(0~4294967295) instead of UNSIGNED_SHORT(0~65535)? Does Cesium support this change?

**Comment by caohaoze** [comment]
UNSIGNED_INT(0, 4294967295)
UNSIGNED_SHORT(0, 65535)

**Comment by lilleyse** [comment]
Yes `UNSIGNED_INT` should work fine.

**Comment by caohaoze** [comment]
OK. Thanks.
