### ISSUE TITLE
3D-tiles style: heightOffset don't change the tiles' elevation

### ISSUE THREAD

**Issue by YingcaiDong** [AnalyticalGraphicsInc/3d-tiles#291]
Hi Everyone!

I'm new to Cesium, and I'm working on a project that loads many 3D building models into Cesium, and for accuracy concern, I have to use the Cesium-World-Terrain as my default terrain provider. Which resulting the 3D building floating in the air. I went through the issues posted here and found that I can modify the model's  elevation using:
`tile.modelMatrix = Cesium.Matrix4.fromTranslation(translation);`

However, that doesn't meet my requirement. Because the terrain has different elevations but the `modelMatrix` can only adjust all the models into the same offset (if I understand correctly), and that causes some building models sank to the underground and some buildings are displayed properly.

Then I found that Cesium support **style** to change the 3D-tiles' property. There is a member in `Cesium3DTileSytle` called `heightOffset` which I think may be able to change tiles' elevation individually. So I wrote a simple code just to test out `heighOffset`:
```
tiles.style = new Cesium.Cesium3DTileStyle({
        color: {
            conditions: [
                ["${height} >= 300", "rgba(45, 0, 75, 0.5)"],
                ["${height} >= 200", "rgb(102, 71, 151)"],
                ["${height} >= 100", "rgb(170, 162, 204)"],
                ["${height} >= 50", "rgb(224, 226, 238)"],
                ["${height} >= 25", "rgb(252, 230, 200)"],
                ["${height} >= 10", "rgb(248, 176, 87)"],
                ["${height} >= 5", "rgb(198, 106, 11)"],
                ["true", "rgb(127, 59, 8)"]
            ]
        },
        heightOffset: {
            conditions: [
                // The 3D-tiles are NYC builds, the average terrain elevation -28
                // So what I want to see is the buildings with the height higher than 2 
                //will be clipped to the ground.
                // This is just a test, I am planning to use globb.getHeight() to get
                //height info for each building model and adjust them using the condition syntax.
                ['${height} > 2', '-28'],
                ['true', '2.0']
            ]
        }
    });
```
However, the heightOffset seems not working as I thought it would be. The buildings are still floating in the air in the terrain model.

So here is my question: 1. do I use the `terrainOffset` correctly? 2. Why is it not working? 3. Is there any other way to adjust each building's height individually?

Best Regards,
Yingcai

**Comment by lilleyse** [comment]
Hi @YingcaiDong 

`heightOffset` is only used by point features in vector tiles. It doesn't work for b3dm tiles. I think our documentation needs to be clearer about this.

Right now it's not possible to adjust the heights of individual features in a b3dm tile. A b3dm is considered to be static and an offset from terrain is typically baked into the geometry.

**Comment by YingcaiDong** [comment]
Hi @lilleyse 

I just figure out how to adjust the elevation dynamically. In the documentation, `Cesium3DTile` has a member called `tileVisible`, so if I add this event to the event listener, then every time a new tile is rendered in the view, I am able to get this tile's [property](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTile.html), and there is a member called [computedTransform](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTile.html#computedTransform) which receive the transformation data. So I was able to adjust elevation for each tile in runtime at least.

Cheers,
Yingcai.

**Comment by lilleyse** [comment]
Ah good idea, I hadn't thought about transforming per tile.

Also `transform` is probably a better choice since `computedTransform` is marked as ready only.

**Comment by lilleyse** [comment]
I opened an issue about the documentation in Cesium: https://github.com/AnalyticalGraphicsInc/cesium/issues/6358

**Comment by YingcaiDong** [comment]
Hi @lilleyse 

Regarding the `transform` and `computedTransform`, in the event listener, if I use `tile.transform` or `tile.modelMatrix`, the build will still float in the air. However, if I use `tile.computedTransform`, then all the building will clip to the ground. I don't know why.

Also, there is a code example for [tileVisible](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html#tileVisible), and as you can see, the example pass color to `tile.content`, which the `content' is also marked as **read only**.

Best,
Yingcai

**Comment by lilleyse** [comment]
Just a quick update: I tried setting `tile.transform` in the `tileVisible` event listener and it seemed to work for me. Maybe my usage is different than yours?

```
tileset.tileVisible.addEventListener(function(tile) {
    // Make buildings jitter randomly
    tile.transform = new Cesium.Matrix4.fromTranslation(new Cesium.Cartesian3(0,0,Math.random()*10.0), new Cesium.Cartesian3());
});
```

**Comment by VISHNUPRAKASHREDDY** [comment]
im new to cesium, can anyone post the solution here, facing similar problem

**Comment by lilleyse** [comment]
Hi @VISHNUPRAKASHREDDY

Could you post more details about the problem you're trying to solve to the [Cesium Community Forum](https://community.cesium.com/)?

**Comment by VISHNUPRAKASHREDDY** [comment]
hi @lilleyse , I have posted my query in forum, heres the link to it 
https://community.cesium.com/t/dynamic-height-adjustment-of-3d-tiles/17375?u=vishnu_prakash_reddy
