### ISSUE TITLE
Oct encoding clarification for pnts and i3dm

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#298]
In [pnts](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/PointCloud) and [i3dm](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Instanced3DModel) make it clearer that oct encoded values are stored in unsigned unnormalized range [0, 65535] or [0, 255] and then converted to a signed normalized range [-1, 1] at runtime.

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
