### ISSUE TITLE
Should Batch Table Hierarchy be an extension?

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#303]
[Batch Table Hierarchy](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/BatchTable#batch-table-hierarchy) is a pretty specialized and not widely used feature of 3D Tiles and conceptually is like an extension. Now that we are adding extension support maybe this could be our first one and help prove out the concept?

Thoughts @ggetz @pjcozzi ?

**Comment by ggetz** [comment]
> The standard batch table is suitable for datasets composed of features with the same sets of properties. However, some datasets have more complex metadata structures such as feature types or feature hierarchies that are not easy to represent as parallel arrays of properties.

The wording of the spec itself sounds like the standard batch table hierarchy should be an extension, and looks like we can easily move the schema over to an extension.

The only thing that may be tricky is how does styling work with extensions? Are the styling language features also part of the extension then?

**Comment by lilleyse** [comment]
Yeah, the new styling language functions would be part of the extension.

**Comment by clausnagel** [comment]
When looking at the most successful data models and formats in the BIM and 3D GIS world (such as IFC, OGC CityGML, OGC IndoorGML, etc.), it quickly becomes obvious that there is a need for rich information beyond pure graphics and triangle meshes, such as nested feature hierachies and thematic attributes on each level of this hierarchy. Simply think of a building that can be decomposed into components such as storeys and rooms, with each component having slabs, roofs, walls and walls having further nested objects such as windows and doors. All of these objects can carry attributes which one wants to be able, for instance, to query or use for styling in a 3D web map.

The Batch Table Hierarchy allows us to group and subgroup triangles to reflect such nested feature hierarchies and to assign meaning and attributes to each subgroup individually. This way the information becomes available in the viewer for sophisticated tasks beyond visualization. I think this is a core feature of 3D Tiles and makes a difference to other platforms that mainly care about triangle meshes. It thus should neither be easily dropped nor outsourced into an extension. 

For our commercial products, we use and rely upon the Batch Table Hierarchy for these reasons.

**Comment by ggetz** [comment]
We moved this to an extension as part of the `1.0` branch effort. I think we'll close all those relevant items once https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301 is merged (which I think might be later today)

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
