### ISSUE TITLE
Post-1.0 version plans

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/3d-tiles#309]
Topic  | Status
---|---
[Vector Data](TileFormats/VectorData/README.md) (*.vctr) _Polygons, polylines, and placemarks_ | :white_circle: **In progress**, [#124](https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/124/files)
Terrain v2  | :white_circle: **Not started**, [quantized-mesh](https://cesiumjs.org/data-and-assets/terrain/formats/quantized-mesh-1.0.html) is a good starting point; in the meantime, folks are using [Batched 3D Model](TileFormats/Batched3DModel/README.md)
[OpenStreetMap](TileFormats/OpenStreetMap/README.md)  | :white_circle: **Not started** Currently folks are using [Batched 3D Model](TileFormats/Batched3DModel/README.md)
Stars  | :white_circle: **Not started**

**Comment by pjcozzi** [comment]
Moved to #247
