### ISSUE TITLE
PNTS: Unclear padding description in the specification

### ISSUE THREAD

**Issue by PissedCapslock** [AnalyticalGraphicsInc/3d-tiles#314]
I am writing my own generator for PNTS files, but I seem to fail to generate PNTS files which can be read by Cesium 1.45 . I know I am doing something wrong with the padding, but I have the impression the Cesium implementation relies on details I either could not find in the specification, or that are not (yet) mentioned.

From the [PointCloud specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/TileFormats/PointCloud#padding), I gathered that the file size must be a multiple of 8 bytes:

> A tile's byteLength must be aligned to an 8-byte boundary. The contained Feature Table and Batch Table must conform to their respective padding requirement.

The [FeatureTable specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/1.0/TileFormats/FeatureTable/README.md#padding) and [BatchTable specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/1.0/TileFormats/BatchTable/README.md#padding) are less clear however:

> The Feature Table binary body must start and end on an 8-byte alignment within the containing tile binary.
> The JSON header must be padded with trailing Space characters (0x20) to satisfy alignment requirements of the Feature Table binary (if present).

The start of the binary body on an 8-byte alignment can indeed be satisfied by padding the JSON header with spaces. However, there is nothing mentioned in how to pad to fulfil the end requirement. 

For example in the binary body of the batch table you can use componentType ``BYTE`` which has a length of one byte. Depending on the number of points or batch ids, this can result in a non-multiple of 8 bytes written to the binary body.

My first idea was to just pad the binary body with spaces at the end to ensure that the end was also aligned to an 8-byte boundary. The specification does not mention if this is the correct approach.

Further, Cesium gave me among others the following error with my incorrect PNTS file:
``Sandcastle-client.js:22 Error: start offset of Float32Array should be a multiple of 4``

Googling on this error message [suggests](https://stackoverflow.com/q/7372124/1076463) that the Javascript implementation requires that the start of a ``float32[3]`` property in the binary body can only be located at certain indices.

To go back to my example with a ``BYTE`` componentType, it would mean that when I first encode a ``BYTE`` property in the binary body followed by a ``float32[3]`` one, I need to pad after the ``BYTE`` property to ensure that the ``float32[3]`` starts at the correct index in the binary body.

I found nothing mentioned about this requirement in the specification, so I am unsure whether I stumbled upon an implementation detail of Cesium, or whether this is intended to be part of the specification which was not mentioned in the padding section.

Would it be possible to clarify the padding requirements in the specification ?

**Comment by lilleyse** [comment]
I made some tweaks to the padding requirements in #308.

Would you mind checking out the latest draft and see if it helps clarify?

https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0-formatting/specification/TileFormats/BatchTable#padding

**Comment by PissedCapslock** [comment]
Thanks for the pointers. I indeed overlooked the mention in the `byteOffset` section.

I think your update is a huge improvement compared to the original text.

**Comment by lilleyse** [comment]
Awesome, thanks again for the feedback.
