### ISSUE TITLE
Explain 3D Tiles spatial data structure for 2D users

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#315]
The spatial data structure in 3D Tiles is non-obvious at first glance to many geospatial developers.  Let's add a short section early on that better explains how the spatial data structure works for someone who already knows about a `z/y/x` (or whatever) quadtree, e.g., how do you bridge their knowledge to a general spatial data structure and motivate why.

@ggetz and @lilleyse please do this for 1.0.

**Comment by ggetz** [comment]
Once we merge https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/308
