### ISSUE TITLE
Bad `type`: UNSIGNED_INT with home-made PNTS file

### ISSUE THREAD

**Issue by PissedCapslock** [AnalyticalGraphicsInc/3d-tiles#316]
When trying to load the attached PNTS data in the Cesium Sandcastle app (http://localhost:8080/Apps/Sandcastle/index.html), I get the following warnings on the console (both in Chrome and Firefox):

``WebGL warning: vertexAttribPointer: Bad `type`: UNSIGNED_INT``

I have generated this PNTS file myself, and there is obviously something wrong with it. Problem is that I have no clue what exactly.

I tried running the [validator](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/validator) on that file, but I don't get any output with the validator (nor any error messages).

Seeing as the message complains about `UNSIGNED_INT`, I would assume something is wrong with the `BATCH_ID` as that is the only `UNSIGNED_INT` I am using. But according to the [spec](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/TileFormats/PointCloud), an `UNSIGNED_INT` is allowed:

> The BATCH_ID semantic may have a componentType of UNSIGNED_BYTE, UNSIGNED_SHORT, or UNSIGNED_INT

Do you have any pointers how I can figure out what is wrong with my PNTS file ? Is there perhaps another validator I can use that outputs clear error messages ?

Note: I kept the file deliberately very small to make it easier to debug it.

[pnts.zip](https://github.com/AnalyticalGraphicsInc/3d-tiles/files/2077464/pnts.zip)

**Comment by lilleyse** [comment]
Thanks @PissedCapslock, it was a Cesium bug. See https://github.com/AnalyticalGraphicsInc/cesium/pull/6666.

**Comment by PissedCapslock** [comment]
A bug which you already fixed. Awesome !
