### ISSUE TITLE
How to adjust 3dtiles model size  to fit for map?

### ISSUE THREAD

**Issue by libofei2004** [AnalyticalGraphicsInc/3d-tiles#317]
I added a 3dtileset model to a map, but it's size  is not fit for the map, how can I resize the model so that it is fit for the map?

**Comment by libofei2004** [comment]
@lilleyse Thank you, I can set tileset.modelMatrix to change the size already, but when I try to set tileset.modelMatrix to rotate the 3dtileset model, I failed. The code is like this:
var m1 = Cesium.Matrix3.fromRotationX(Cesium.Math.toRadians(60));
 Cesium.Matrix4.multiplyByMatrix3(m,m1,m);
The position of the model has moved to another place very far from original position.

**Comment by lilleyse** [comment]
What is the value of `m`? The matrix multiplication order might need to be flipped depending on whether `m` contains a scale or translation.

**Comment by libofei2004** [comment]
@lilleyse 
//url "../Specs/Data/Cesium3DTiles/Tilesets/TilesetWithTransforms" is in CesiumJS archive folders   
var tileset = new Cesium.Cesium3DTileset({
      url: "../Specs/Data/Cesium3DTiles/Tilesets/TilesetWithTransforms" 
});
viewer.scene.primitives.add(tileset);
var m = tileset.modelMatrix;
