### ISSUE TITLE
Point Cloud Rendering Through Terrain

### ISSUE THREAD

**Issue by ProjectBarks** [AnalyticalGraphicsInc/3d-tiles#319]
I am using Cesium3DTiles to display point cloud tiles and have a rendering artifact where the points render through the terrain. I have put a screenshot below to demonstrate the problem I am experiencing.
![Screenshot](https://i.imgur.com/7D3BEeD.png)

I was wondering if there is any way to re-prioritize render order so only the points visible to the user render. My thought if this was not possible was to use a style that updates when the camera moves around 3D space and add a formula based off distance to the user to decide if the point should render.

**Comment by lilleyse** [comment]
Hi @ProjectBarks, nice screenshot. It looks like an interesting project.

Try `viewer.scene.globe.depthTestAgainstrTerrain = true`. That will hide points that are occluded by terrain.

Some of the more dynamic show styles you mention will be possible eventually with [mutables](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/252) for which there is a work in progress Cesium [PR](https://github.com/AnalyticalGraphicsInc/cesium/pull/5380).

Also for future reference the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev) is a better place for general usage questions like this.

**Comment by ProjectBarks** [comment]
Thank you will do. But for anyone who finds the thread the appropriate selector is
`viewer.scene.globe.depthTestAgainstTerrain = true`

**Comment by lilleyse** [comment]
Ah sorry about the typo. I updated my comment.
