### ISSUE TITLE
Batch Table changes

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#32]
From #23:

* [x] Throughout 3D Tiles, should `batchTable` be renamed?  Something like `propertyTable`, `metadataTable`, etc.
* [x] Throughout 3D Tiles, should the `batchTable` work more like glTF buffer/bufferView/accessor to avoid arrays of numbers?

**Comment by pjcozzi** [comment]
>  Throughout 3D Tiles, should batchTable be renamed?

Discussed with @lilleyse offline.  We're going to keep `batchTable`.

**Comment by lilleyse** [comment]
Some ideas for adding a binary section to the batch table to store properties like colors, normals, scales, etc in a more space-efficient way:

Usually the batch table stores an array of values, like:

```javascript
{
    "id" : ["unique id", "another unique id"],
    "displayName" : ["Building name", "Another building name"],
    "scale" : [1.0, 1.4]
}
```

But for numeric data like scale it is more efficient to store in a binary form. The property in the batch table can instead reference a chunk of binary data like:

```javascript
{
    "id" : ["unique id", "another unique id"],
    "displayName" : ["Building name", "Another building name"],
    "scale" : {
        "byteOffset" : 0,
        "componentType" : "FLOAT",
        "type" : "SCALAR"
}
```

Where:
* `byteOffset` is the offset from the start of the `batchTableBinary`.
* `componentType` can be the following values: `"BYTE"`, `"UNSIGNED_BYTE"`, `"SHORT"`, `"UNSIGNED_SHORT"`, `"FLOAT"`, and `"DOUBLE"`
* `type` can be `"SCALAR"`, `"VEC2"`, `"VEC3"`, `"VEC4"`, `"MAT2"`, `"MAT3"`, `"MAT4"`

The data is assumed to be tightly packed, so we are not using a `byteStride` variable for now.

Well known semantics that the client understands how to process like rgb, scale, and normal should be labelled as `3DTILES_RGB`, `3DTILES_SCALE`, `3DTILES_NORMAL`. For these properties the `componentType` and `type` are optional.

Every tile format will need to change to support the batch table binary section. `batchTable` will be broken into `batchTableJson` and `batchTableBinary`, and `batchTableLength` in the header will be replaced by two values `batchTableJsonLength` and `batchTableBinaryLength`. Like the batch table itself, `batchTableBinary` is optional.

**Comment by pjcozzi** [comment]
+1 from me!

**Comment by pjcozzi** [comment]
Cesium implementation PR by @lilleyse - https://github.com/AnalyticalGraphicsInc/cesium/pull/4112

**Comment by pjcozzi** [comment]
* [ ] We should do #103 as part of this.

**Comment by pjcozzi** [comment]
Spec updates: #4183

**Comment by pjcozzi** [comment]
#125 will be merged shortly.
