### ISSUE TITLE
Gltf 2.0 in I3DM

### ISSUE THREAD

**Issue by crubier** [AnalyticalGraphicsInc/3d-tiles#322]
Hi, I am aware of #94 , but it seems related only to B3DM. 

I would like to use Gltf 2.0 models in an instantiated tileset and this does not work right now. Any Ideas on how to make it work ? Is it possible already ?

**Comment by lilleyse** [comment]
It is possible already. What is the problem you're seeing?

If it helps you can review the spec from the [1.0 branch](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0), which has standardized on glTF 2.0 for b3dm and i3dm.

**Comment by crubier** [comment]
Ok perfect thank you !
