### ISSUE TITLE
How can I open and read b3dm file??

### ISSUE THREAD

**Issue by Juuungi** [AnalyticalGraphicsInc/3d-tiles#323]
I'm a totally newbie in this area. I need to read a header of b3dm file. I used eclipse and read the file but I realized I can't read header section cuz it's binary section. Is there some tools to read it? I just want to read a source code of my b3dm file

**Comment by lilleyse** [comment]
Discussion moved here: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/issues/148.
