### ISSUE TITLE
EPSG 4979 or EPSG 4326

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#324]
Someone in the community asked?

> The region bounding volume specifies bounds using a geographic coordinate system (latitude, longitude, height), specifically EPSG 4326.

EPSG 4326 is 2D. Don't you mean EPSG 4979?

**Comment by ggetz** [comment]
yes, [EPSG:4979](http://spatialreference.org/ref/epsg/4979/) includes height above the ellipsoid, whereas 4326 does not. Will update accordingly.

**Comment by lilleyse** [comment]
Fixed in #325
