### ISSUE TITLE
3dTiles generate tool？

### ISSUE THREAD

**Issue by GISerWYJ** [AnalyticalGraphicsInc/3d-tiles#332]
I can't find an official 3dtile generation tool, I've tried using FME ,but it's not working,  3dtile spec has become a ogc standard, I am looking foward a official tool , which  can help us save a lot time, thank you!

**Comment by ggetz** [comment]
3D Tiles is currently undergoing consideration to become an OGC community standard. We have [3d-tiles-tools](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools) for generating sample data, and we offer some [tools and services](https://cesium.com/collaborate-with-us/#data-services) for various types of data.

**Comment by ggetz** [comment]
Also take a look at the CLI tools we currently have for converting to 3D tiles:

 * [CityGML](https://cesium.com/3d-tiling-pipeline/citygml/)
 * [Photogrammetry](https://cesium.com/3d-tiling-pipeline/photogrammetry/)
 * [Point Clouds](https://cesium.com/3d-tiling-pipeline/pointclouds/)

And we're working on more!
