### ISSUE TITLE
hello,question about pnts.

### ISSUE THREAD

**Issue by chenlongfromchina** [AnalyticalGraphicsInc/3d-tiles#335]
i am new about point cloud,i want to write a tool about .las convert to .pnts ,but i do not understand about this  formula POSITION = POSITION_QUANTIZED * QUANTIZED_VOLUME_SCALE / 65535.0 + QUANTIZED_VOLUME_OFFSET,i can get POSITION from .las using liblas, can you tell me how to define QUANTIZED_VOLUME_SCALE and QUANTIZED_VOLUME_OFFSET,thank you!

**Comment by ggetz** [comment]
Hi @chenlongfromchina,

See [this section of the spec](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/TileFormats/PointCloud#quantized-positions) for an explanation of quantized positions.

Generally, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. We use GitHub for feature requests and bug tracking exclusively.
