### ISSUE TITLE
3d-tiles 1.49 loading issue

### ISSUE THREAD

**Issue by NatKov** [AnalyticalGraphicsInc/3d-tiles#336]
Hello, dear community.
The new 1.49 seems not to load all the levels of 3d-tiles. At certain angles and scales parts of 3d-tiles are missing from the display. This type of behavior was never observed using previous versions. 
Attached an example of the same data and code based on 1.48 vs 1.49 build

![tiles_issue](https://user-images.githubusercontent.com/39759030/45149612-a8eaaa80-b1d2-11e8-96b2-32c4f42480c2.JPG)

Links to the sample project:
[http://simplex-smart3d.com/ces/sample/app_tiles_1.49/](url)
[http://simplex-smart3d.com/ces/sample/app_tiles_1.48/](url)

Will be happy if you review this issue. Thanks.

**Comment by lilleyse** [comment]
Thanks for the report @NatKov. I think I've tracked down the bug but it would help if you could verify it with your tileset.

The fix is here: https://github.com/AnalyticalGraphicsInc/cesium/pull/7011

You can download a build of the branch from http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/refinement-fix/Cesium-1.49.0-refinement-fix28520.zip

**Comment by NatKov** [comment]
@lilleyse, sorry for the delay, I am currently on vacation..
My team checked the fix on the tileset I provided and there’re no display gaps as before. Thanks for such a quick response!
However something is still not perfect with the level of details - it’s hard to pinpoint it, but seems like not all the information is loading at certain scales. I will try to provide more information when I will be back to work.

**Comment by lilleyse** [comment]
That new problem sounds like something else we fixed recently: https://github.com/AnalyticalGraphicsInc/cesium/pull/7035

Here's a new build to try: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Cesium-1.49.0-master28667.zip
