### ISSUE TITLE
3DTILES_batch_table_hierarchy extension example tileset

### ISSUE THREAD

**Issue by jailln** [AnalyticalGraphicsInc/3d-tiles#339]
Hi,
Is there an example tileset with the 3DTILES_batch_table_hierarchy extension available in open access ?

**Comment by lilleyse** [comment]
Yes, check out the [BatchTableHierarchy](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Apps/SampleData/Cesium3DTiles/Hierarchy/BatchTableHierarchy) tileset  which is generated from the [3D Tiles Samples Generator](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/samples-generator).

**Comment by jailln** [comment]
Great, thanks :)
