### ISSUE TITLE
Load tiles with fade-in

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/3d-tiles#343]
This [came up on the forum](https://groups.google.com/d/msg/cesium-dev/p19tY12e7v0/S54N7RqpCwAJ). I initially thought it might just be something Cesium can do, but @ggetz suggested it might better to be part of the spec, to define a way to control how the tiles load, whether they should just pop in as they currently do or fade in. 

I think either way it would be a simpler thing to add that might make everything look a lot nicer.

**Comment by pjcozzi** [comment]
I don't think this has anything to do with the spec; this should be a runtime engine decision.  Currently tracking in https://github.com/AnalyticalGraphicsInc/cesium/issues/3241
