### ISSUE TITLE
Unclear BATCH_ID type of feature table of id3m

### ISSUE THREAD

**Issue by vipcxj** [AnalyticalGraphicsInc/3d-tiles#346]
The document said it could be uint8, uint16 (default), or uint32. However without a fixed component type, we can not locate it in the binary body by offset. So can anyone give me an example to show how it works?

**Comment by lilleyse** [comment]
For certain properties like BATCH_ID you may override the default component type.

From https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/TileFormats/FeatureTable#json-header:

> Some semantics allow for overriding the implicit component type. These cases are specified in each tile format, e.g., "BATCH_ID" : { "byteOffset" : 24, "componentType" : "UNSIGNED_BYTE"}.

I opened a PR to add this to the schema: https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/348

**Comment by vipcxj** [comment]
Could any property listed in the feature table schema be override the type by the property `componentType` or just `BATCH_ID`. If there is `componentType` in a binary reference of property other than `BATCH_ID`, how should I deal with it？

**Comment by lilleyse** [comment]
`BATCH_ID` is the only one that can override it right now, and even then it can only be one of the three options in the [semantics table](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/TileFormats/Instanced3DModel#instance-semantics).

If a loader sees a `componentType` that is isn't allowed it should throw an error.
