### ISSUE TITLE
EAST_NORTH_UP is not listed in the schema of i3dm.featureTable

### ISSUE THREAD

**Issue by vipcxj** [AnalyticalGraphicsInc/3d-tiles#347]
EAST_NORTH_UP is not listed in the schema of i3dm.featureTable. And its type `Boolean` is ambiguous. I don't know its size in byte.

**Comment by lilleyse** [comment]
Thanks for noticing this. `RTC_CENTER` was also missing from the schema. I double checked the other tile formats and they look good.

`EAST_NORTH_UP` is now defined as a `globalPropertyBoolean` type. It can only be `true` or `false` in JSON, and cannot be stored in the feature table binary. That should clear up the ambiguity.

@vipcxj feel free to leave any feedback on https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/349 or https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/348.
