### ISSUE TITLE
How RGBA value save in bytes?

### ISSUE THREAD

**Issue by vipcxj** [AnalyticalGraphicsInc/3d-tiles#350]
For example, [10. 20. 30. 40] means R = 10, G = 20, B = 30, A = 40 or A = 10, R = 20, G = 30, B = 40?

**Comment by lilleyse** [comment]
This is for point cloud colors right? The order is R = 10, G = 20, B = 30, A = 40.

**Comment by vipcxj** [comment]
Thanks for reply.
