### ISSUE TITLE
How RGB565 save in bytes?

### ISSUE THREAD

**Issue by vipcxj** [AnalyticalGraphicsInc/3d-tiles#351]
It seems that RGB565 is endian-specific. I want to develop a java based 3d-tiles impl. However java is a big-endian platform. So How can I load the rgb565 color from byte array in java.
1. I load a short value from bytes array under little-endian way. This means the short value combines as `bytes[1] bytes[0]`
2. I load the high 5 bytes from the short value as the red value.
3. I load the next high 6 bytes from the short value as the green value.
4. I load the left 5 bytes from the short value as the blue value.

e.x.
```java
byte[] bytes = [0x12, 0x34];
short shortValue = 0x3412; //0b0011 0100 0001 0010
byte r = 0b00110;
byte g = 0b100000;
byte b = 0b10010;
```

Is that right?
Or there is another solution, load the data just as the bytes order: `bytes[0], bytes[1]`
1. I load the high 5 bytes from the bytes[0] as red value.
2. I load the left 3 bytes of bytes[0] combines with the high 3 bytes of bytes[1] as green value.
3. I load the left 5 bytes of bytes[1] as blue value.

e.x.
```java
byte[] bytes = [0x12, 0x34]; //[0b0001 0010, 0b0011 0100]
byte r = 0b00010;
byte g = 0b010001;
byte b = 0b10100;
```

**Comment by lilleyse** [comment]
I think your approach is fine. But if it helps, Cesium uses bit shifting to avoid any endianness issues. A GLSL implementation is here: 

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/PointCloud.js#L1100-L1107

**Comment by vipcxj** [comment]
Which approach is right? Bit shifting is not able to avoid the endianness issues. The key is that short value is endian-specific. In a little endian platform, the first byte of the byte array is the low part of the short value.  
For example
```java
byte[] bytes = [0x12, 0x34];
short shortValue = 0x3412; // bytes[0] | bytes[1] << 8
```
If we choose the high 5 bit of the `shortValue` as red value, it equals choosing high 5 bit of `bytes[1]` as red value. This is my first approach.
However, if I don't treat the rgb value as whole, but a byte array of length 2. Then I choose the high 5 bit of `bytes[0]` as red value. This is my second approach.
By google, it seems that RGB565 really is endian-specific. Perhaps the second approach is wrong.

**Comment by vipcxj** [comment]
By the way, my java library only process the 3d tiles file, doesn't render it. But I want it support color format transforming. So I need what really the bit of the color data means.

**Comment by vipcxj** [comment]
It seems that Cesium read the rgb565 color data as a short array first. So it seems that my first approach is right. However, I found it is not clear the endian of the typed array by google.
This [link](https://stackoverflow.com/questions/7869752/javascript-typed-arrays-and-endianness) shows that
> The current behaviour, somewhat sadly, is that the endianness is that of the underlying hardware. As almost all desktop computers are x86, this means little-endian. Most ARM OSes use little-endian mode (ARM processors are bi-endian and thus can operate in either).
