### ISSUE TITLE
Gltf is 4-byte aligned, but all tile file is 8-byte aligned.

### ISSUE THREAD

**Issue by vipcxj** [AnalyticalGraphicsInc/3d-tiles#357]
The spec require all part of file to be 8-byte aligned, but gltf is 4-byte aligned, Should I padding some bytes to the end of the gltf part?

**Comment by vipcxj** [comment]
But perhaps glb has more than two chunk or there is only a  json chunk, no binary chunk. Padding data to the end of json chunk seems better.

**Comment by lilleyse** [comment]
Yes, that works too.
