### ISSUE TITLE
Do you provide build tools for ply?

### ISSUE THREAD

**Issue by soulgoast** [AnalyticalGraphicsInc/3d-tiles#364]
we need a tool from *.ply or *.gltf to *.pnts.

**Comment by Sanlings** [comment]
https://www.cesiumlab.com/  This website may help you. 

![image](https://user-images.githubusercontent.com/45448582/50626775-2220c100-0f6b-11e9-820d-4022406925b0.png)

![image](https://user-images.githubusercontent.com/45448582/50626764-05848900-0f6b-11e9-8234-c9bbc19313a0.png)
