### ISSUE TITLE
Is there any style expression function like Array.IndexOf()

### ISSUE THREAD

**Issue by hanaimin** [AnalyticalGraphicsInc/3d-tiles#365]
In my batch table, I has a array typed column named 'ids' which stores the data like ["AA|XXXX","BB|XXXX yysfdf","CC|dfdsf|dfssxx"]
In my idea, the 'ids' column is used to styling. if the array value ${ids}.indexOf(some value) !== -1, then color the feature.

But I can not found any style expression function like Array.indexOf.

I try to use regExp and convert the array to string "String(${ids})", but it's not good enough for the problem, because String(${ids}) is too many chars to get good performance. Another reason is that the id string  contains many unexpected chars conflicting with regex expression.

**Comment by lilleyse** [comment]
The styling language doesn't have many array or string functions yet, so unfortunately there isn't a simple way to do `indexOf`. The regex approach you wrote seems like an ok solution as long as any special characters in the search string are escaped. At runtime the style usually only gets evaluated when the tile is loaded or if a feature property changes so performance might not be too much of a concern.

You could also try some other ideas for storing metadata. If there aren't too many value types you could store them as boolean arrays or batch table binary properties (to reduce size). And if your metadata is hierarchical you could check out the [batch table hierarchy](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/extensions/3DTILES_batch_table_hierarchy) extension.
