### ISSUE TITLE
Is it possible to position the instance in i3dm with position (0, 0, 0)?

### ISSUE THREAD

**Issue by vipcxj** [AnalyticalGraphicsInc/3d-tiles#369]
There is a transform in tile too. So it seems that we can transform the model from gltf coordinate to the earth coordinate in tile layer. However the option 'EAST_NORTH_UP' need rotation computing depend on the earth coordinate. So I am confused that what really position should be. On the other hand, if the position make the model just on the ground. A scale in the tile layer will make the model fly to the sky, it seems not what we commonly want.

**Comment by lilleyse** [comment]
If you're using a tile transform to position instances on the globe it is usually best for the instance positions to be in local coordinates (0,0,0) and not use the `EAST_NORTH_UP` option. If the transform contains scale it should scale the tile first and then apply the translation/rotation, which I think is the behavior you want.

The other approach is to use `RTC_CENTER` to store the center in global coordinates, set `POSITION` values to be relative to the center, and use `EAST_NORTH_UP` to apply the correct orientation.
