### ISSUE TITLE
Reference doc for tiles.json

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#37]
* [ ] Generate it using [wetzel](https://github.com/AnalyticalGraphicsInc/wetzel) like we did for glTF.
* [ ] Needs https://github.com/AnalyticalGraphicsInc/wetzel/issues/5

This will be one of the last things we do so we know the schema is stable.

**Comment by bagnell** [comment]
* [ ] Generate the vector tile styling tables from the schema.

**Comment by lilleyse** [comment]
Yes, done in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/308
