### ISSUE TITLE
How should I calculate the geometric error of a point cloud file?

### ISSUE THREAD

**Issue by VinoKobe24** [AnalyticalGraphicsInc/3d-tiles#370]
I have divided the point cloud data into octree and divided the lod level, but I can't calculate the effective geometric error. How should this be calculated? Thank you

**Comment by pjcozzi** [comment]
The geometric error is the "number of meters" wrong the tile is compared to rendering the full-resolution "ground truth" version - this computation will depend on how you are generating the LOD.
