### ISSUE TITLE
how to transform b3dm file from sphere to box or region

### ISSUE THREAD

**Issue by weskerjiang** [AnalyticalGraphicsInc/3d-tiles#371]
My b3dm's tileset.json is like 
"root":{
		"boundingVolume":{
			"sphere":[-2891967.4829483447,4725280.2949528517,3149936.8351058047,656.64834117889404]
		}

but i want to use box or region ,how to change?

**Comment by OmarShehata** [comment]
How did you generate your tileset?

This would typically be something to do while generating the tileset as opposed to after the fact I think. There are some helper functions that parse these in CesiumJS that might help here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Cesium3DTile.js#L1074-L1087

So you could take the sphere and compute the cube it would be inscribed in, which would use the radius as its half length:

https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#box

**Comment by weskerjiang** [comment]
> 
> 
> How did you generate your tileset?
> 
> This would typically be something to do while generating the tileset as opposed to after the fact I think. There are some helper functions that parse these in CesiumJS that might help here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Cesium3DTile.js#L1074-L1087
> 
> So you could take the sphere and compute the cube it would be inscribed in, which would use the radius as its half length:
> 
> https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#box

We use ContextCapture to generate our tileset,it can transform to the b3dm file from osgb,but it can only create sphere bounding.So you mean to do that while generating,not after,right?

**Comment by OmarShehata** [comment]
Ideally ContextCapture could add an option for this yeah, but you should be able to write a script to do this re-processing after.

**Comment by pjcozzi** [comment]
Good discussing.  Closing to keep this GitHub repo focused on 3D Tiles spec issues.
