### ISSUE TITLE
3dtail memory leak

### ISSUE THREAD

**Issue by PrUnSt** [AnalyticalGraphicsInc/3d-tiles#373]
After the tile is removed, it disappears from view. Why is the memory not released?
If I keep loading and removing, the browser will crash. Why

**Comment by OmarShehata** [comment]
Are you experiencing this in CesiumJS or a different viewer?

**Comment by PrUnSt** [comment]
in CesiumJS.
I converted 3dtail from my model,use Cesium load ,I didn't do anything and then b3dm gets loaded and removed all the time

**Comment by OmarShehata** [comment]
How did you create the 3D Tiles from your model?

Can you share a code example (like on Sandcastle https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) to show what's happening?

**Comment by PrUnSt** [comment]
After I replaced the b3dm data, this problem never occurred again.....
