### ISSUE TITLE
3dtiles will disappear at some angles

### ISSUE THREAD

**Issue by caipeng-hrv** [AnalyticalGraphicsInc/3d-tiles#374]
![appear](https://user-images.githubusercontent.com/7042328/58141364-bae37f00-7c75-11e9-8a8a-ef35aed782d1.png)
![disappear](https://user-images.githubusercontent.com/7042328/58141369-bfa83300-7c75-11e9-8b08-582f7bc7a997.png)
Can someone tell me what happened?

**Comment by OmarShehata** [comment]
@lilleyse this was answered here https://github.com/AnalyticalGraphicsInc/cesium/issues/7859 so we can close this.
