### ISSUE TITLE
I3dm format

### ISSUE THREAD

**Issue by wangyuan8876** [AnalyticalGraphicsInc/3d-tiles#375]
In the i3dm how I write for quoting the uri of glb?

**Comment by lilleyse** [comment]
The uri does not contain quotes. If you view this sample i3dm as utf-8 you can see there aren't quotes around `box.glb`:

[InstancedGltfExternal.zip](https://github.com/AnalyticalGraphicsInc/3d-tiles/files/3227742/InstancedGltfExternal.zip)

**Comment by wangyuan8876** [comment]
Thank you! I have get it

**Comment by wangyuan8876** [comment]
Cesium.js:2098 The embedded glb is not aligned to a 4-byte boundary. I have add the space at the end,but it is no use.

**Comment by wangyuan8876** [comment]
![image](https://user-images.githubusercontent.com/30743049/58550894-5e69fc00-8241-11e9-84a2-dd3e6b9db5aa.png)
![image](https://user-images.githubusercontent.com/30743049/58550903-63c74680-8241-11e9-9207-f5df83223b81.png)
I can't find the i3dm model ,why?the position i have set!

**Comment by pjcozzi** [comment]
@wangyuan8876 this sounds like an implementation question for your 3D Tiles exporter.  We try to keep this GitHub repo focused on the 3D Tiles spec itself so I am going to close this to keep the repo issues manageable.  If you still need help, I think the Cesium forum would be a good place to continue the conversation: http://cesiumjs.org/forum

**Comment by wangyuan8876** [comment]
thank you very much！I have solved it! it is my question.
