### ISSUE TITLE
Bim i3dm

### ISSUE THREAD

**Issue by wangyuan8876** [AnalyticalGraphicsInc/3d-tiles#377]

**Comment by wangyuan8876** [comment]
![image](https://user-images.githubusercontent.com/30743049/58625287-b9b0f280-8304-11e9-9b31-0f55065f8e8a.png)
please who hnow how to set the orientation of the Z axis.

**Comment by pjcozzi** [comment]
@wangyuan8876 this sounds like an implementation question for your 3D Tiles exporter.  We try to keep this GitHub repo focused on the 3D Tiles spec itself so I am going to close this to keep the repo issues manageable.  If you still need help, I think the Cesium forum would be a good place to continue the conversation: http://cesiumjs.org/forum
