### ISSUE TITLE
How to get parameters （urgent）

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/3d-tiles#378]
I want the perspective to jump to the target object.
What I know now is the bounding box of the target object.
I know to use viewer.camera.flyToBoundingSphere.
But how should I get the entry?

**Comment by simonasdmd** [comment]
![image](https://user-images.githubusercontent.com/42527845/58621917-ff69bd00-82fc-11e9-8ec6-20b5f77a71fe.png)
What I know now is the bounding box of the target object.
But how should the above entry be obtained?

**Comment by lilleyse** [comment]
@simonasdmd please ask your question on the [Cesium forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev). The `3d-tiles` repo is meant for discussion about the 3D Tiles spec not usage in CesiumJS.
