### ISSUE TITLE
Question about external tileset transformation

### ISSUE THREAD

**Issue by yzthr** [AnalyticalGraphicsInc/3d-tiles#380]
There are two tilesets, and i use a tileset.json to put them together into one tileset. These two tilesets both have same transformation matrix(called [T0]). So i use identity matrix in "parent tileset"(called [E]), The final transform will be [E][T0].BUT when i use cesium.js to load this 3d-tiles, i can't find my model at all.
   Next, i copy the marix of children tileset([T0]) to the parent tileset and set transform matrix of children tileset to identity matrix([E]). then i can load my model successfully.
    [E][T0] equals to [T0][E] ([E] is identity matrix), right? But the result is wired. 
    Any advices will be appreciated!

**Comment by OmarShehata** [comment]
Are you able to share a code example and your tileset to reproduce this? Have you tried using the 3D Tiles inspector (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Inspector.html) to visualize the bounding volumes to see if it's at the right place?

**Comment by yzthr** [comment]
I build a new repository: [](https://github.com/yzthr/hongkong3dtiles)
In this repository, tileset.json outside the two folders was created by me. I moved "transform" node from two tilesets in folders to the one that i built outside the folder. (Two transform node in each tilesets in folders are the same). 
I use cesium.js to open the tileset, the view towards the ocean, but i can't find the model at all. Bounding volume can't be seen either.

**Comment by rainliang000** [comment]
in your "tile_19_25_CESIUM/tileset.json", the transform matrix is transform from globe center to global surface(coordinates 0,0), not really math "identity matrix", it should be 
        "transform": [
            1.0, 0.0,  0.0,  0.0,
            0.0, 1.0,  0.0,  0.0,
            0.0, 0.0,  1.0,  0.0,
            0.0, 0.0,  0.0,  1.0
        ],

**Comment by yzthr** [comment]
Sorry, I uploaded wrong child tileset.json(now updated to the origal one). You can alter the transform matrix on your own. The question also exist.

**Comment by yzthr** [comment]
> in your file "tile_19_25_CESIUM/tileset.json", the transform matrix is transform from globe center to globe surface(coordinates 0,0), not really math "identity matrix", it should be
> "transform": [
> 1.0, 0.0, 0.0, 0.0,
> 0.0, 1.0, 0.0, 0.0,
> 0.0, 0.0, 1.0, 0.0,
> 0.0, 0.0, 0.0, 1.0
> ],

Sorry, I uploaded wrong child tileset.json(now updated to the origal one). You can alter the transform matrix on your own. The question also exist.

**Comment by pjcozzi** [comment]
@yzthr sounds like this may be an issue in your 3D Tiles exporter.  We try to keep this GitHub repo focused on the 3D Tiles spec itself so I am going to close this to keep the repo issues manageable.  If you still need help, I think the Cesium forum would be a good place to continue the conversation: http://cesiumjs.org/forum
