### ISSUE TITLE
cesium 1.62 pbr rendering effect question

### ISSUE THREAD

**Issue by fdzhaofei** [AnalyticalGraphicsInc/3d-tiles#392]
I found cesium-1.62 pbrmaterial is rather dim than cesium-1.61!
Is there any param I need set？Look forward to your reply!
                                                                             Best regards！
                                                                                      John!
<img src="https://s2.ax1x.com/2019/11/01/KH1BaF.jpg" alt="KH1BaF.jpg" border="0">
<img src="https://s2.ax1x.com/2019/11/01/KH10VU.jpg" alt="KH10VU.jpg" border="0">

**Comment by OmarShehata** [comment]
You can see all the updates in 1.62 in the changelog:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#162---2019-10-01

Notice that the IBL parameters changed. This was done here: https://github.com/AnalyticalGraphicsInc/cesium/pull/8156.

So you can change this by setting the luminanceAtZentih parameter: https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html#luminanceAtZenith
