### ISSUE TITLE
ECEF is EPSG:4978, not 4979

### ISSUE THREAD

**Issue by plutoscarab** [AnalyticalGraphicsInc/3d-tiles#393]
CRS section of specification says "A tileset's global coordinate system will often be in a WGS 84 earth-centered, earth-fixed (ECEF) reference frame (EPSG 4979)"

4979 is lat/lon/alt, whereas [4978 is ECEF](https://epsg.io/4978).

**Comment by OmarShehata** [comment]
I think you're right. The later paragraph that talks about positioning the region with lat/lon/alt is correct then:

> The region bounding volume specifies bounds using a geographic coordinate system (latitude, longitude, height), specifically EPSG 4979.

But since the top paragraph seems to be talking about x/y/z it should be 4978. @lilleyse can you confirm?

**Comment by lilleyse** [comment]
Yes WGS84 ECEF should be 4978. Good catch @plutoscarab. I'll open a PR.

**Comment by ladislavhorky** [comment]
Hi @OmarShehata, @lilleyse the typo is frozen in the latest OGC standard, causing possible confusion (http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html#25). Is there a way to fix it there as well?
