### ISSUE TITLE
3DTILES_batch_table_hierarchy example inconsistencies

### ISSUE THREAD

**Issue by FreakTheMighty** [AnalyticalGraphicsInc/3d-tiles#398]
I'm struggling to understand the example provided at the end of the 3DTILES_batch_table_hierarchy spec. A few things are confusing me.

![batch-table-hierarchy-block](https://user-images.githubusercontent.com/247092/71384852-afa05b00-2598-11ea-9ec2-f12087acdb5f.png)

1. Shouldn't batchId 3 map to the 4th element in the classIds array? In the car example batch Id 5 maps to the 5th element in the classIds array.
1. In the building example, the third classId is also the third occurrence of id `0`, however it maps to the 4th instance in wall class. In the "car" example the third occurrence of class ID 1, maps to the third instance. Which is correct, or am I missing a step in how these are mapped?
1. In the building example, how can batchId 2 and 3 reference the same building? They can't be the second occurrence of class 1.

Thanks in advance for your help clarifying these issues.

**Comment by lilleyse** [comment]
@FreakTheMighty  It looks like the diagram does have a mistake. It should be this:

![Capture](https://user-images.githubusercontent.com/915398/71389614-176f9980-25cb-11ea-9489-691ceb4b8efd.PNG)

I think this clears up your first two questions, not positive about the third.

Thanks for catching this.

**Comment by FreakTheMighty** [comment]
Thanks @lilleyse that does clear up my first two questions. Let me try asking the third a different way. 

If the diagram shows batch ID 2 and 3 as part of the same building, does the data structure show both batch ids sharing a building name?

**Comment by FreakTheMighty** [comment]
Aah, now I see. With the corrected index, they both point to the 7th index, so they would both point to the same instance  in the building class.

**Comment by lilleyse** [comment]
@FreakTheMighty Yes, exactly. The original mistake made everything more confusing, sorry about that.

This is a good starter spec issue @sanjeetsuhag.

**Comment by FreakTheMighty** [comment]
No worries! Thanks for the quick response.
