### ISSUE TITLE
Question about "REPLACE" refinement mode

### ISSUE THREAD

**Issue by topheg** [AnalyticalGraphicsInc/3d-tiles#401]
Hello,
I'm wondering how the "REPLACE" mode works when there also is "ADD" mode used in the tree:
* Let's suppose tile level N has "refine":"ADD"
Then the content of tiles level N+1 will be added to the content of tile level N.
* Then, tiles level N+1 have "refine":"REPLACE"
When tiles level N+2 are shown they replace the content of tiles level N+1. 
Do they also replace the contents of tile level N, or is tile N still visible ?

Thank you !

**Comment by lilleyse** [comment]
The tile at level N would still be visible.

**Comment by topheg** [comment]
Thanks for the quick answer !
