### ISSUE TITLE
Change asset.version to 1.0

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#54]
Change all the examples in this repo and Cesium once the spec stabilizes.

CC #50.

**Comment by pjcozzi** [comment]
Also change the examples in the `cesium` and `3d-tiles-samples` repo.

**Comment by lilleyse** [comment]
And `3d-tiles-tools` generator project.

**Comment by pjcozzi** [comment]
Pull request: #234

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/234
