### ISSUE TITLE
MIME types for tile formats

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#60]
Cesium's Node.js development server is using `application/octet-stream` for now.

Related glTF discussion: https://github.com/KhronosGroup/glTF/issues/412

**Comment by emackey** [comment]
Just a reminder, IIS will not serve any files with unknown file extensions.  So if you've defined new file extensions for 3D tiles, but not added them explicitly to `web.config`, then IIS-based installations won't be able to access those files.

**Comment by pjcozzi** [comment]
Cesium's web.config was updated in #3468.

**Comment by pjcozzi** [comment]
Current tileset.json MIME type: `application/json`

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301

**Comment by thw0rted** [comment]
I don't think #301 resolved all the mime types for the various tile formats -- c.f. [point cloud](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/TileFormats/PointCloud/README.md) which is still listed as `application/octet-stream`.  The various other tile formats include the same TODO item with a reference to this ticket.

**Comment by ggetz** [comment]
Changes are in the `1.0` branch - See https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/specification/TileFormats/PointCloud#file-extension-and-mime-type
