### ISSUE TITLE
Should tiles always be gzipped?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#61]
Currently, Cesium is storing all of the tile formats gzipped compressed.  Should this be part of the core spec, e.g., a `.b3dm` file is always gzipped compressed?

One concern is if problem-domain specific compression (mesh compression, point cloud compression, etc.) cancels out any benefit of gzip.

Perhaps we want the flexibility that some tile playloads will be gzipped and others will not so we just leave this out of the spec?

**Comment by lilleyse** [comment]
Along the same lines as you mentioned, I think enforcing gzip compression is too restrictive for the spec.

**Comment by mramato** [comment]
> Along the same lines as you mentioned, I think enforcing gzip compression is too restrictive for the spec.

@lilleyse the goal here would be to make 3D Tiles tilesets easily interchangeable.  The question we need to answer is "Should a 3D Tiles server be able to serve any 3D tileset?"  If the answer is yes, then it has to be part of the spec (or somehow have a server-side component that informs the server regarding compression).  If the answer is no, then it will be impossible to serve a tileset without knowing additional information not available in the tileset itself.

**Comment by jbo023** [comment]
We would prefer that gzipping or not falls in the responsibilities of the webserver admin. 

Our workflow always creates uncompressed data files (b3dm, terrain, quantized mesh). 
This makes deploying the files to a default webserver easier. (You don't have to set the gzip header in the apache config).

If gzipping makes sense we activate dynamic gzipping on the webserver or create a static gzipped dataset and set the header in the apache configuration.

**Comment by pjcozzi** [comment]
Thanks for the input, @jbo023.

**Comment by pjcozzi** [comment]
A comment from https://groups.google.com/forum/#!topic/cesium-dev/EPjCzYgmIxo

> there are multiple issues that i discovered when using my own http server rather than the server.js supplied.
>
> 1. the encoding type for the b3dm and pnt files need to be 'gzip'
otherwise nothing is displayed and no error..... very very painful.

**Comment by pjcozzi** [comment]
Caught another user: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/87#issuecomment-199423329

**Comment by pjcozzi** [comment]
Given that this has confused several users - including me at times - and that some mesh compression algorithms do not benefit from gzip (for example, see OpenCTM [here](http://www.max-limper.de/publications/CaseStudy2013/CaseStudy2013.pdf)), we are not going to require tiles be gzipped as part of the spec.

The Cesium sample data will not be served gzipped so it is easy for users to inspect.  Users are free to serve gzipped or not in their own server implementations.  We can add a comment to the spec that tiles may be served gzipped.

I'm going to make this change soon so please comment ASAP if there are any concerns.
