### ISSUE TITLE
Update tileset schema to reflect required properties

### ISSUE THREAD

**Issue by e-andersson** [AnalyticalGraphicsInc/3d-tiles#63]
Cesium now throws an exception when `"asset": { "version": 0.0}` is missing from `tileset.json`, so if that's the desired behavior it should be reflected in the schema. Judging from the example `tileset.json` https://github.com/AnalyticalGraphicsInc/3d-tiles#tilesetjson there may be other updates needed.

**Comment by pjcozzi** [comment]
What exactly needs to be updated?

`asset` and `version` are marked as required in the schema:
* https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/tileset.schema.json
* https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/asset.schema.json

**Comment by e-andersson** [comment]
Sorry, my mistake -- didn't see the separate asset schema...

**Comment by pjcozzi** [comment]
All good.  Thanks for keeping us honest!
