### ISSUE TITLE
Relative URLs in external tileset.json

### ISSUE THREAD

**Issue by clausnagel** [AnalyticalGraphicsInc/3d-tiles#67]
I am currently experimenting with external tilesets and came across a question with relative URLs.
Assume a tileset `a.json` with a `content.url` pointing to another tileset `b.json`. `b.json` contains a `content.url` to a `tile.b3dm` content file. Further assume that `a.json` and `b.json` are not in the same path.
 
Now, my assumption was that a relative `content.url` to `tile.b3dm` must be given relative to `b.json` because it is referenced from this tileset. However, I was surprised to learn that it has to be relative to `a.json`. Is this the supposed behavior?

Cheers,
Claus

**Comment by lilleyse** [comment]
Thanks for bringing this up, a tile url should be relative to its tileset and not just the root tileset. I opened a pull request in Cesium: https://github.com/AnalyticalGraphicsInc/cesium/pull/3529

**Comment by pjcozzi** [comment]
Thanks for the report, @clausnagel, and for the fix, @lilleyse.

I tweaked the wording in #68 to make this more explicit.

**Comment by pjcozzi** [comment]
@lilleyse please close this when you merge #68.
