### ISSUE TITLE
How are extensions handled?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#8]
Extensions in both tiles.json and the tiles themselves.  We'll most likely take the same approach as glTF (for tiles.json) and quantized-mesh (for tiles).

Does tiles.json support both `extensions` and `extras` like glTF?  Perhaps `extra` is useful for application-specific per-tile metadata that the app could process with a load event.  We need concrete use cases.

**Comment by pjcozzi** [comment]
For now the schema has `"additionalProperties" : false` for all dictionary objects.

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
