### ISSUE TITLE
Reference glTF 2.0 spec

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#94]
For example, update [here](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel#binary-gltf) and elsewhere to be glTF 2.0, not glTF 1.0.

glTF 2.0 updates: https://github.com/KhronosGroup/glTF/issues/605

Also consider if there are any other glTF extensions, like unsigned int indices, that we want to include.

**Comment by pjcozzi** [comment]
CC https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/issues/15

**Comment by nitrologic** [comment]
What is the status of b3dm? If there is no immediate plan to adopt GLTF 2.0 then perhaps this spec should be considered abandonware and a deprecation notice added.

**Comment by pjcozzi** [comment]
@nitrologic Cesium's 3D Tiles renderer implementation supports glTF 2.0 - and converts glTF 1.0 to 2.0 on-the-fly for backwards compatibility - this issue is a reminder to update the b3dm/i3dm spec before we put the finishing touches on it for a final 1.0.

**Comment by nitrologic** [comment]
Thanks for the prompt reply Patrick. I have yet to see a 2.0 based b3dm in the wild so was concerned my failure to create a conforming asset was due to not reading the fine print which currently states  "Batched 3D Model uses glTF 1.0 with the KHR_binary_glTF extension."

**Comment by pjcozzi** [comment]
I believe the same tilesets in the Cesium repo are glTF 2.0.

**Comment by nitrologic** [comment]
Exactly which tilesets in what repo?

**Comment by lilleyse** [comment]
I actually don't think they have been updated yet. I have a branch in `3d-tiles-tools` but haven't had a chance to finish it up yet: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/2.0-samples-generator

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
