### ISSUE TITLE
OSM to Cesium

### ISSUE THREAD

**Issue by stirringhalo** [AnalyticalGraphicsInc/3d-tiles#96]
Looking into getting buildings (and possibly other features), I started toying with the OSM2World project again. Now that OBJ2GLTF exists, it's easy to get OSM into Cesium.

For example: https://github.com/stirringhalo/osm2cesium

![Sample image of New York](https://raw.githubusercontent.com/stirringhalo/osm2cesium/master/sample2.png)

This takes OSM extracts and dumps them to obj, which is then converted to gltf, and georeferenced in Cesium based on the original obj

I've heard mention of a gltf to b3dm converter, does such a tool exist now or on the horizon? I'm looking to expand osm2cesium to handle larger areas with streaming.

**Comment by pjcozzi** [comment]
Nice job with osm2cesium, @stirringhalo!

I am not aware of any open-source glTF to b3dm converters at this time.

See [this post](https://groups.google.com/forum/#!topic/cesium-dev/AQ5qsl8l-JI) on the Cesium forum.
