### ISSUE TITLE
one complete fileb3dm ascII file in which all content can be read

### ISSUE THREAD

**Issue by liyihongcug** [AnalyticalGraphicsInc/3d-tiles#97]
I want to create one 3-d tiles b3dm edit Tool.
who can give me the b3dm ascII file which content can't be ???  and I can't understand. 
My requirements are below:
1  one complete fileb3dm ascII file in which all content can be read. please notice this webstie sample are not suitable;
2  I am ready for developing it in Java. I want to know how to generate one b3dm file from one gltf in detail?

**Comment by pjcozzi** [comment]
b3dm is binary, not ASCII.  It is basically a header + batch table + binary glTF as described here: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Batched3DModel#layout

Please post questions like this on the [Cesium forum](http://cesiumjs.org/forum.html) and use GitHub issues in this repo for spec-related discussion.
