### ISSUE TITLE
Per-tileset or per-tile transform

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#98]
WGS84 is not appropriate for all tilesets.  For example, the inside of a building or a point cloud may be relative to local coordinate system.

This could be solved by adding a 4x4 `modelMatrix` (or `matrix` like glTF, or maybe `transform`) to `tileset.json`, which transforms the tileset's local coordinates to WGS84.  This would default to being the identity matrix, meaning that the local coordinate system is WGS84.

Alternatively, each tile in `tileset.json`could have a 4x4 `modelMatrix` that transforms to the parent's coordinate system (this would include the bounding volume), which provides more flexibility and is standard in the computer graphics community, but has a bit more complexity.  This is most likely the right approach to elegantly support heterogeneous tilesets of tilesets.

**Comment by GatorScott** [comment]
A matrix won't suffice if the transformation is complex as in the U.S. State Plane coordinate system which can be one of two projected coordinate systems, Transverse Mercator or Lambert Conformal Conic.

**Comment by pjcozzi** [comment]
The spirit of 3D Tiles is similar to the spirit of glTF - keep the client fast and simple (well, simple-ish) and put heavy work that can be done offline to the server so I would not encourage us adding more complex transforms that would, for example, require clients to include proj.4 in order to have a complete implementation.

**Comment by pjcozzi** [comment]
@lilleyse for the spec, what do you think of an optional per-tile column-major 4x4 matrix named `transform` that is concatenated top-down at runtime just like glTF, including tilesets of tilesets?  It defaults to identity and the root tileset world space is still WGS84?

Example:
```javascript
{
  // ..
  "root": {
    "transform": [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 7000000, 0, 0, 1]
    "boundingVolume": {
      "box" : {
        // ...
      }
    },
    "content": {
      "boundingVolume": {
         // ...
      },
      "url": "0/0/0.b3dm"
    },
    "geometricError": 268.37878244706053,
    "refine": "add",
    "children": [
      {
        "boundingVolume": {
          "region": [
            // in WGS84 despite any transform properties
          ]
        },
        "content": {
          "boundingVolume": {
            // ...
          },
          "url": "1/0/0.b3dm"
        },
```

This would apply to the bounding volume and all geometry in tiles.  **However, it does not apply to region**, which is cartographic and fixed in WGS84.

Spatial coherence in world space must still exist (no need to expose the ability to change the transform at this point in the Cesium API; however, this could become useful, definitely a top-level `modelMatrix`, which, btw, I added when I did the original point cloud prototype).

I think `transform` is the right term since `matrix` is not general in the 3D Tiles context (it is OK in glTF though) and `modelMatrix` isn't right since this is really the `local` matrix used to compute the `model` matrix.

**Comment by lilleyse** [comment]
This is definitely useful to have and easy to implement.

**Comment by pjcozzi** [comment]
For the spec:

* [ ] `geometricError` is always in meters; the scale of the `transform` matrix does not affect it.

**Comment by pjcozzi** [comment]
For the spec:

* [ ] External tileset tile `transform` must match root tile's `transform`, https://github.com/AnalyticalGraphicsInc/cesium/pull/4130#issuecomment-233322636

**Comment by lilleyse** [comment]
I think there may be cases where the above point is too restrictive. What if you have a point cloud of a building that is relative to 0.0 and you would like to position it anywhere on the globe?

**Comment by pjcozzi** [comment]
For this case, the root of the point cloud tileset would have the transform from the local to world (or another local coordinate system).  The tile whose content points to this point cloud tileset just needs to have the same matrix so the semantics line up with external tilesets in general.

**Comment by lilleyse** [comment]
What I mean is, the author of the point cloud tileset may not know where the data will be positioned. Putting the local to world matrix in the point cloud root is forcing it to a certain location. What if two different tilesets reference this point cloud and want to position the data in different areas of the globe?

**Comment by lilleyse** [comment]
If this isn't a common enough use case, I'm fine with them having the same transforms for simplicity.

**Comment by pjcozzi** [comment]
Ah, very good point so let's apply both transforms.  This complicates the spec a bit (which now says the tile is "semantically the same as the external tileset's root tile so"), but it is justified.

**Comment by pjcozzi** [comment]
For the spec:

* [ ] External tilesets apply both `transforms` (replaces above, https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/98#issuecomment-233322790)

**Comment by pjcozzi** [comment]
Cesium implementation: https://github.com/AnalyticalGraphicsInc/cesium/pull/4130

**Comment by pjcozzi** [comment]
Spec update: #123
